// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicLayout: typeof import('./layouts/BasicLayout.vue')['default']
    BlankLayout: typeof import('./layouts/BlankLayout.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
  }
}

export { }
